<?php

namespace Database\Seeders;

use App\Models\Service;
use Illuminate\Database\Seeder;

class ServiceSeeder extends Seeder
{
    public function run(): void
    {
        $services = [
            [
                'name' => 'Airport Transfer',
                'slug' => 'airport-transfer',
                'icon' => 'paper-airplane',
                'hero_image_url' => '/images/services/airport-transfer.jpg',
                'sort_order' => 1,
                'short_description' => 'Seamless door-to-door airport transfers across Ghana. We monitor your flight in real time so you never wait.',
                'description' => '<p>Arriving at Kotoka International Airport or Kumasi Airport? Uprise takes the stress out of your journey. Our professional drivers track your flight status in real time and adjust pickup timing automatically for delays. Expect a name-board meet-and-greet at arrivals, ice-cold complimentary water, and swift, silent transit to your destination.</p><p>We cover all major airports in Ghana and can arrange cross-border airport pickups on request. Available 24/7, 365 days a year.</p>',
                'meta_title' => 'Airport Transfer Ghana | Kotoka Airport Pickup & Drop-off | Uprise',
                'meta_description' => 'Professional airport transfer service in Ghana. Flight tracking, meet & greet at Kotoka International Airport (ACC) and Kumasi Airport. Available 24/7.',
            ],
            [
                'name' => 'Executive Chauffeur',
                'slug' => 'executive-chauffeur',
                'icon' => 'star',
                'hero_image_url' => '/images/services/executive-chauffeur.jpg',
                'sort_order' => 2,
                'short_description' => 'Hourly and daily executive chauffeur hire. Discreet, professional, always on time.',
                'description' => '<p>For business leaders, diplomats and VIP clients who demand more than a taxi. Our executive chauffeur service puts a professionally-trained, English-speaking driver at your disposal by the hour or day. Whether it\'s a full day of back-to-back meetings in Accra or a multi-city itinerary across Ghana, your chauffeur will keep you on schedule, informed, and relaxed.</p><p>All executive chauffeur vehicles are immaculately maintained premium sedans or luxury SUVs, fitted with Wi-Fi, phone charging, and chilled beverages on request.</p>',
                'meta_title' => 'Executive Chauffeur Service Ghana | Hourly & Daily Hire | Uprise',
                'meta_description' => 'Premium executive chauffeur hire in Ghana. Professional, discreet drivers by the hour or day. Luxury sedans and SUVs. Book your Accra chauffeur today.',
            ],
            [
                'name' => 'Corporate Travel',
                'slug' => 'corporate-travel',
                'icon' => 'briefcase',
                'hero_image_url' => '/images/services/corporate-travel.jpg',
                'sort_order' => 3,
                'short_description' => 'Dedicated fleet management for businesses. Centrally billed, monthly reporting, priority dispatch.',
                'description' => '<p>Uprise partners with corporations, embassies, NGOs and multinationals across Ghana to manage their ground transportation needs end-to-end. From daily executive commutes to conference shuttle fleets, we operate as a seamless extension of your operations team.</p><p>Benefits include centralized billing with detailed monthly reporting, a dedicated account manager, priority vehicle allocation, and a diverse fleet capable of handling single VIP pickups or 200-seat conference shuttles simultaneously.</p>',
                'meta_title' => 'Corporate Transportation Ghana | Business Fleet Services | Uprise',
                'meta_description' => 'Corporate ground transportation for businesses and embassies in Ghana. Dedicated fleet, central billing, monthly reporting. Request a corporate account.',
            ],
            [
                'name' => 'Safari & Wildlife Tours',
                'slug' => 'safari-wildlife',
                'icon' => 'sun',
                'hero_image_url' => '/images/services/safari-wildlife.jpg',
                'sort_order' => 4,
                'short_description' => 'Guided 4×4 safari excursions to Mole National Park, Kakum, Paga Crocodile Pond and across Northern Ghana.',
                'description' => '<p>Ghana\'s natural wonders deserve a vehicle that can handle them. Our purpose-built 4×4 Land Cruisers and Fortuners are the transport of choice for Mole National Park safaris, Kakum National Park canopy walks, the Paga Crocodile Pond, Wli Waterfalls and the upper regions of Ghana.</p><p>Packages are fully customizable: day trip from Accra, multi-day northern Ghana circuits, or bespoke West Africa overland journeys. All safari vehicles come with experienced drivers who double as local guides.</p>',
                'meta_title' => 'Ghana Safari Transport | Mole National Park 4x4 Tours | Uprise',
                'meta_description' => 'Reliable 4x4 safari transport to Mole National Park, Kakum and Northern Ghana. Experienced driver-guides, Land Cruisers, customizable tours. Book now.',
            ],
            [
                'name' => 'Group & Event Transfers',
                'slug' => 'group-event-transfers',
                'icon' => 'users',
                'hero_image_url' => '/images/services/group-event-transfers.jpg',
                'sort_order' => 5,
                'short_description' => 'Minivans, coaches and coordinated fleets for conferences, weddings, concerts and large events.',
                'description' => '<p>Moving groups seamlessly is a logistical art. Uprise has transported guest lists for international conferences at AICC, wedding parties across Greater Accra, festival-goers, and corporate team outings with fleets of 2 to 20 vehicles operating in tight coordination.</p><p>Our event transport coordinator works with your team in advance to map routes, stagger pickup windows and ensure every guest arrives on time. Vehicles range from 7-seater Sprinters to 30-seat coaches depending on your group size.</p>',
                'meta_title' => 'Group Transport Ghana | Event Shuttle Service Accra | Uprise',
                'meta_description' => 'Professional group and event transportation in Ghana. Minivans, coaches, coordinated fleets for conferences, weddings and corporate events. Get a quote.',
            ],
            [
                'name' => 'Wedding Car Service',
                'slug' => 'wedding-car',
                'icon' => 'heart',
                'hero_image_url' => '/images/services/wedding-car.jpg',
                'sort_order' => 6,
                'short_description' => 'Luxury bridal cars and coordinated guest shuttles for your perfect day.',
                'description' => '<p>Your wedding day deserves perfection at every turn. Uprise provides beautifully presented luxury vehicles for bridal parties, a dedicated coordinator to manage your transport schedule, and a support team on-site throughout the event. We handle the logistics so you can focus entirely on your most important day.</p><p>Choose from our fleet of premium sedans, luxury SUVs and Sprinters. We also coordinate guest shuttle services between venues for larger celebrations.</p>',
                'meta_title' => 'Wedding Car Hire Ghana | Bridal Transportation Accra | Uprise',
                'meta_description' => 'Luxury wedding car hire in Ghana. Bridal cars, guest shuttles, on-site coordination. Beautiful fleet for your perfect wedding day in Accra and beyond.',
            ],
            [
                'name' => 'Cape Coast & Heritage Day Tours',
                'slug' => 'cape-coast-day-tours',
                'icon' => 'map',
                'hero_image_url' => '/images/services/cape-coast-day-tours.jpg',
                'sort_order' => 7,
                'short_description' => 'Day tours from Accra or Takoradi to Cape Coast, Elmina and the coast — ideal for cruise ship passengers and heritage travelers.',
                'description' => '<p>Cape Coast is Ghana\'s most powerful heritage destination — home to Cape Coast Castle and Elmina Castle, both UNESCO World Heritage Sites and cornerstones of the transatlantic slave trade story. Uprise provides comfortable, private day tours with professional drivers who can take you from Accra or Takoradi at your pace.</p><p>This service is particularly popular with cruise ship passengers arriving at Takoradi Port who want a full-day guided road experience before sailing. We handle pickup, transport, and drop-off logistics so you don\'t miss your ship. Custom itineraries available on request.</p>',
                'meta_title' => 'Cape Coast Day Tours Ghana | Cruise Ship Shore Excursions | Uprise',
                'meta_description' => 'Private day tours to Cape Coast and Elmina Castles from Accra or Takoradi. Ideal for cruise ship passengers. Professional drivers, flexible itineraries.',
                'is_active' => true,
            ],
            [
                'name' => 'Cross-Border Travel',
                'slug' => 'cross-border-travel',
                'icon' => 'globe-alt',
                'hero_image_url' => '/images/services/cross-border-travel.jpg',
                'sort_order' => 8,
                'short_description' => 'Accra to Lagos, Lomé, Abidjan and beyond — experienced drivers, immaculate vehicles, border-crossing expertise.',
                'description' => '<p>West Africa\'s most important business corridors connect Accra to Lagos, Lomé, Cotonou, Abidjan and Ouagadougou. Uprise operates premium cross-border transport on these routes with drivers who know the border procedures, road conditions and optimal routes by heart.</p><p>All vehicles are fully insured for cross-border travel, properly documented for ECOWAS transit, and stocked for long-haul comfort. We also handle Togo, Benin, and Ivory Coast routes for diplomatic and corporate clients.</p>',
                'meta_title' => 'Cross-Border Transport West Africa | Accra to Lagos, Lomé | Uprise',
                'meta_description' => 'Premium cross-border ground transportation from Ghana to Nigeria, Togo, Benin and Ivory Coast. Experienced drivers, fully insured. Book your cross-border transfer.',
            ],
            [
                'name' => 'Ghana Car Rentals',
                'slug' => 'ghana-car-rentals',
                'icon' => 'map',
                'hero_image_url' => '/images/services/ghana-car-rentals.jpg',
                'sort_order' => 9,
                'short_description' => 'Car hire with a professional driver anywhere in Ghana — Accra, Kumasi, Tamale, Cape Coast, Mole and beyond.',
                'description' => '<p>Whether you need a car for a day, a week, or a full itinerary across Ghana, Uprise provides reliable, driver-included hire nationwide. Every booking comes with a vetted professional driver who knows the roads, the checkpoints, and the best routes between Ghana\'s cities and destinations.</p><p>We cover all major destinations including Accra, Kumasi, Tamale, Cape Coast, Elmina, Bolgatanga, Wa, and Mole National Park. Cross-border hire to Togo and Benin is also available on request.</p>',
                'meta_title' => 'Ghana Car Rentals with Driver | Nationwide Hire | Uprise Travel',
                'meta_description' => 'Hire a car with a professional driver anywhere in Ghana. Accra, Kumasi, Tamale, Cape Coast, Mole and more. All-inclusive, driver-included car rental service.',
            ],
            [
                'name' => 'Accra Car Rentals',
                'slug' => 'accra-car-rentals',
                'icon' => 'map-pin',
                'hero_image_url' => '/images/services/accra-car-rentals.jpg',
                'sort_order' => 10,
                'short_description' => 'Daily and weekly car hire with a professional driver across Accra — Airport Hills, Osu, East Legon, Cantonments and the greater Accra region.',
                'description' => '<p>Accra is Ghana\'s busiest city and navigating it without a reliable driver is a challenge. Uprise provides professional driver-included car hire across all of Greater Accra — whether you need a half-day for meetings, a full day of errands, or a week-long executive arrangement.</p><p>Our drivers know every neighbourhood: Airport Hills, Osu, East Legon, Cantonments, Labone, Spintex Road, Tema, and beyond. Available for corporate accounts, diaspora visitors, NGO professionals, and leisure travellers alike.</p>',
                'meta_title' => 'Accra Car Rentals with Driver | Daily & Weekly Hire | Uprise Travel',
                'meta_description' => 'Professional car hire with driver in Accra, Ghana. Airport Hills, Osu, East Legon, Cantonments and all of Greater Accra. Book your Accra driver today.',
            ],
            [
                'name' => 'Accra Airport Pickups',
                'slug' => 'accra-airport-pickups',
                'icon' => 'paper-airplane',
                'hero_image_url' => '/images/services/accra-airport-pickups.jpg',
                'sort_order' => 11,
                'short_description' => 'Meet-and-greet airport transfers at Kotoka International Airport (ACC). We track your flight so your driver is always ready.',
                'description' => '<p>Arriving at Kotoka International Airport? Uprise makes your Accra arrival seamless. Our drivers track your flight in real time and adjust pickup timing automatically — no waiting, no confusion at arrivals.</p><p>Expect a name-board meet-and-greet in the arrivals hall, assistance with your luggage, and smooth transfer to your hotel, residence, or office anywhere in Greater Accra. Available 24 hours a day, 7 days a week including public holidays.</p>',
                'meta_title' => 'Accra Airport Pickup | Kotoka International Airport Transfer | Uprise',
                'meta_description' => 'Professional airport pickup at Kotoka International Airport (ACC), Accra. Flight tracking, meet & greet, 24/7 availability. Book your Accra airport transfer.',
            ],
            [
                'name' => 'Tamale Airport Pickups',
                'slug' => 'tamale-airport-pickups',
                'icon' => 'paper-airplane',
                'hero_image_url' => '/images/services/tamale-airport-pickups.jpg',
                'sort_order' => 12,
                'short_description' => 'Airport transfers at Tamale Airport (TML) — the gateway to Northern Ghana, Mole National Park and the Upper Regions.',
                'description' => '<p>Flying into Tamale? Uprise provides reliable airport pickup and drop-off at Tamale Airport (TML) — the main gateway to Northern Ghana. Whether you\'re heading into Tamale city, continuing to Mole National Park, Bolgatanga, Wa, or anywhere across the north, your driver will be waiting.</p><p>Our northern Ghana drivers are experienced on the roads between Tamale and all upper-region destinations. We track your flight and confirm your driver\'s position before you land.</p>',
                'meta_title' => 'Tamale Airport Pickup | Northern Ghana Airport Transfer | Uprise',
                'meta_description' => 'Airport transfer at Tamale Airport (TML). Pickup and drop-off for Tamale, Mole National Park, Bolgatanga and Northern Ghana. Professional driver included.',
            ],
            [
                'name' => 'Tamale Car Rentals',
                'slug' => 'tamale-car-rentals',
                'icon' => 'map-pin',
                'hero_image_url' => '/images/services/tamale-car-rentals.jpg',
                'sort_order' => 13,
                'short_description' => 'Car hire with driver in Tamale and across Northern Ghana — ideal for NGO work, development sector travel and northern region exploration.',
                'description' => '<p>Tamale is the capital of Northern Ghana and the staging point for Mole National Park, Larabanga Mosque, Bolgatanga, Wa and the Upper Regions. Uprise provides reliable driver-included car hire in Tamale for NGO and development sector professionals, corporate travellers, and leisure visitors exploring the north.</p><p>Our Tamale-based drivers understand the roads, conditions, and logistics of northern Ghana. Available for day hire, multi-day arrangements, and full northern Ghana circuits.</p>',
                'meta_title' => 'Tamale Car Rentals with Driver | Northern Ghana Hire | Uprise Travel',
                'meta_description' => 'Car hire with professional driver in Tamale and Northern Ghana. Ideal for NGO travel, Mole National Park trips and northern region exploration.',
            ],
            [
                'name' => 'Kumasi Car Rentals',
                'slug' => 'kumasi-car-rentals',
                'icon' => 'map-pin',
                'hero_image_url' => '/images/services/kumasi-car-rentals.jpg',
                'sort_order' => 14,
                'short_description' => 'Professional driver-included car hire in Kumasi — Ghana\'s second city and the heart of the Ashanti Region.',
                'description' => '<p>Kumasi is Ghana\'s second-largest city and the cultural capital of the Ashanti Region. Whether you\'re visiting for business, attending a funeral or festival, exploring Manhyia Palace, or using Kumasi as a base for onward travel, Uprise provides reliable driver-included car hire throughout the city and region.</p><p>We cover Kumasi Central, Kejetia, Manhyia, KNUST, Adum, and surrounding areas. Transfers between Kumasi and Accra, Cape Coast, or Tamale are also available.</p>',
                'meta_title' => 'Kumasi Car Rentals with Driver | Ashanti Region Hire | Uprise Travel',
                'meta_description' => 'Car hire with professional driver in Kumasi, Ghana. Ashanti Region, city transfers, KNUST, Manhyia and more. Book your Kumasi driver today.',
            ],
            [
                'name' => 'Cape Coast Car Rentals',
                'slug' => 'cape-coast-car-rentals',
                'icon' => 'map-pin',
                'hero_image_url' => '/images/services/cape-coast-car-rentals.jpg',
                'sort_order' => 15,
                'short_description' => 'Car hire in Cape Coast and the Central Region — UNESCO World Heritage sites, Kakum National Park and the coast.',
                'description' => '<p>Cape Coast is home to two UNESCO World Heritage Sites — Cape Coast Castle and Elmina Castle — and one of Ghana\'s most visited destinations for heritage tourism. Uprise provides professional driver-included car hire for visitors exploring Cape Coast, Elmina, Kakum National Park, and the Central Region coastline.</p><p>We offer day trips from Accra, multi-day Central Region itineraries, and local hire within Cape Coast. Our drivers are familiar with the heritage sites, tourism operators, and logistics of the region.</p>',
                'meta_title' => 'Cape Coast Car Rentals | Central Region Driver Hire | Uprise Travel',
                'meta_description' => 'Car hire with driver in Cape Coast, Ghana. Cape Coast Castle, Elmina, Kakum National Park. Day trips from Accra and local Central Region hire available.',
            ],
            [
                'name' => 'Mole National Park Car Rentals',
                'slug' => 'mole-national-park',
                'icon' => 'sun',
                'hero_image_url' => '/images/services/mole-national-park.jpg',
                'sort_order' => 16,
                'short_description' => 'Dedicated 4×4 transport to and within Mole National Park — Ghana\'s largest wildlife reserve and premier safari destination.',
                'description' => '<p>Mole National Park is Ghana\'s largest wildlife reserve and home to elephants, buffalo, antelope, warthogs, and over 300 bird species. Getting there and exploring it properly requires the right vehicle and a driver who knows the terrain.</p><p>Uprise provides purpose-built 4×4 Land Cruisers and Fortuners for Mole transfers from Accra or Tamale, as well as in-park transport for multi-day safari stays. Our drivers are experienced on the unpaved roads around Mole Motel and the park\'s interior tracks. We also arrange Larabanga Mosque stops and Damongo day trips en route.</p>',
                'meta_title' => 'Mole National Park Transport | 4x4 Safari Transfer Ghana | Uprise',
                'meta_description' => 'Reliable 4x4 car hire for Mole National Park, Ghana. Transfers from Accra or Tamale, in-park transport, experienced safari drivers. Book your Mole trip today.',
            ],
        ];

        foreach ($services as $data) {
            Service::updateOrCreate(['slug' => $data['slug']], $data);
        }
    }
}
